FROM ghcr.io/insight-platform/manylinux_2_28_x64:v0.0.5 as builder

WORKDIR /opt
COPY . .
ENV LD_LIBRARY_PATH="/usr/lib64/pulseaudio:$LD_LIBRARY_PATH"
ARG PYTHON_INTERPRETER
RUN bash /opt/docker/build-manylinux.sh
RUN rm -rf target

FROM alpine:3.18 as dist
COPY --from=builder /opt/dist /opt/dist